version: '3.8'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'django'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'django'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1004012'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1004012Admin'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - django_db:/var/lib/mysql


  web:
    image: askosyrev/test_fe_web:latest
    restart: always

#    build: .
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code
    ports:
      - "8000:8000"
#    environment:
#      - POSTGRES_NAME=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db


# Names our volume
volumes:
  django_db: